# Generated by Django 5.0.9 on 2026-08-20 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Wifi",
                        help_text="lucide-react icon name",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="Compass", max_length=50)),
                (
                    "category",
                    models.CharField(blank=True, default="Explore", max_length=100),
                ),
                (
                    "distance",
                    models.CharField(
                        blank=True, help_text="e.g. 2.5 km", max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="attractions/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("open_time", models.TimeField(default="08:00")),
                ("close_time", models.TimeField(default="22:00")),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Business Hours",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Contact Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(default="+91 98765 43210", max_length=30)),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="919876543210",
                        help_text="Digits only with country code, no + or spaces",
                        max_length=30,
                    ),
                ),
                (
                    "whatsapp_default_message",
                    models.CharField(
                        default="Hi, I would like to check room availability and pricing. Please share more details.",
                        max_length=300,
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@cozyhomestay.com", max_length=254),
                ),
                (
                    "address",
                    models.CharField(
                        default="123 Palm Grove Road, Coastal Town, India",
                        max_length=300,
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        default="5 mins from the beach promenade",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="A Glimpse of Your Next Escape.", max_length=150
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="video/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Use this OR upload a file above"
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(blank=True, null=True, upload_to="video/"),
                ),
            ],
            options={
                "verbose_name": "Featured Video",
                "verbose_name_plural": "Featured Video",
            },
        ),
        migrations.CreateModel(
            name="GoogleMapsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed src URL (Maps > Share > Embed a map)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, default=15.2993, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=74.124, max_digits=9),
                ),
                ("zoom", models.PositiveIntegerField(default=14)),
                ("directions_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Google Maps Setting",
                "verbose_name_plural": "Google Maps Settings",
            },
        ),
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="A Boutique Escape", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Stay Beyond the Ordinary.", max_length=200
                    ),
                ),
                (
                    "subheading",
                    models.TextField(
                        default="Discover a stay where comfort feels personal, every corner tells a story, and every moment is designed to slow you down."
                    ),
                ),
                (
                    "rotating_keywords",
                    models.CharField(
                        default="Comfort,Calm,Connection",
                        help_text="Comma separated words animated in the hero (e.g. Comfort,Calm,Connection)",
                        max_length=300,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        help_text="Optional short background video",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, default="Handpicked Boutique Stay", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Content",
                "verbose_name_plural": "Hero Content",
            },
        ),
        migrations.CreateModel(
            name="PropertyHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("experience", "Property Experience"),
                            ("why_love", "Why Guests Love Staying"),
                        ],
                        default="experience",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Sparkles",
                        help_text="lucide-react icon name, e.g. BedDouble",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Property Highlight",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("property", "Featured Property"),
                            ("experience", "Featured Experience"),
                        ],
                        default="property",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Not Just a Room. Your Personal Escape.", max_length=200
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        default="Tucked away from the noise of everyday life, our homestay was built on a simple idea: hospitality should feel personal. Every room is thoughtfully designed for peaceful rest, every corner carries the warmth of local character, and every guest is treated like family. We sit minutes from the places you actually want to explore, so you spend less time travelling and more time living the experience."
                    ),
                ),
                ("guests_served", models.PositiveIntegerField(default=5000)),
                (
                    "guest_rating",
                    models.DecimalField(decimal_places=1, default=4.9, max_digits=2),
                ),
                ("years_of_hospitality", models.PositiveIntegerField(default=10)),
                (
                    "support_availability",
                    models.CharField(default="24/7", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Property Info",
                "verbose_name_plural": "Property Info",
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Cozy Homestay | Stay Beyond the Ordinary",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="A premium boutique homestay offering peaceful, personal and comfortable stays.",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        default="homestay, boutique hotel, luxury stay",
                        max_length=300,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/"),
                ),
            ],
            options={
                "verbose_name": "SEO Setting",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter / X"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StayJourneyStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="CalendarCheck", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("room_stayed", models.CharField(blank=True, max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("quote", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Cozy Homestay", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Stay Beyond the Ordinary.", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Website Setting",
                "verbose_name_plural": "Website Settings",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "bed_type",
                    models.CharField(default="King/Queen Bed", max_length=100),
                ),
                (
                    "size_sqft",
                    models.PositiveIntegerField(
                        default=250, help_text="Room size in sq. ft."
                    ),
                ),
                ("max_guests", models.PositiveIntegerField(default=2)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="rooms/")),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="rooms", to="hotel.amenity"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BookingEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                ("rooms_requested", models.PositiveIntegerField(default=1)),
                ("special_request", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_enquiries",
                        to="hotel.room",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Booking Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
