# Generated by Django 5.2.17 on 2026-08-20 16:00

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=hotel.models.video_storage,
                upload_to="video/",
            ),
        ),
        migrations.AlterField(
            model_name="herocontent",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Optional short background video",
                null=True,
                storage=hotel.models.video_storage,
                upload_to="hero/",
            ),
        ),
    ]