// Used only when the Django API is unreachable, so the premium experience
// still renders content-rich in local preview / static hosting scenarios.
export const FALLBACK_CONTENT = {
  settings: { site_name: "Cozy Homestay", tagline: "Stay Beyond the Ordinary.", currency_symbol: "₹" },
  hero: {
    eyebrow: "A Boutique Escape",
    heading: "Stay Beyond the Ordinary.",
    subheading:
      "Discover a stay where comfort feels personal, every corner tells a story, and every moment is designed to slow you down.",
    keywords: ["Comfort", "Calm", "Connection"],
    badge_text: "Handpicked Boutique Stay",
    hero_image: null,
  },
  property: {
    heading: "Not Just a Room. Your Personal Escape.",
    story:
      "Tucked away from the noise of everyday life, our homestay was built on a simple idea: hospitality should feel personal. Every room is thoughtfully designed for peaceful rest, every corner carries the warmth of local character, and every guest is treated like family. We sit minutes from the places you actually want to explore, so you spend less time travelling and more time living the experience.",
    guests_served: 5000,
    guest_rating: "4.9",
    years_of_hospitality: 10,
    support_availability: "24/7",
    highlights: [
      { id: 1, icon: "BedDouble", title: "Rest Well", description: "Comfortable rooms designed for peaceful sleep." },
      { id: 2, icon: "SunMedium", title: "Wake Up Refreshed", description: "Enjoy a calm environment and a relaxing start to your day." },
      { id: 3, icon: "Wifi", title: "Stay Connected", description: "Fast Wi-Fi and essential modern conveniences." },
      { id: 4, icon: "Heart", title: "Feel at Home", description: "Warm hospitality and personalized support throughout your stay." },
      { id: 5, icon: "Compass", title: "Explore Nearby", description: "Convenient access to local attractions and experiences." },
      { id: 6, icon: "Luggage", title: "Travel Without Stress", description: "Easy booking, direct contact and helpful assistance." },
    ],
    why_love: [
      { id: 1, icon: "HandHeart", title: "Warm Hospitality", description: "Our team focuses on making every guest feel comfortable and welcome." },
      { id: 2, icon: "Leaf", title: "Peaceful Environment", description: "A relaxing place designed to help you slow down." },
      { id: 3, icon: "BedDouble", title: "Comfortable Accommodation", description: "Clean, well-maintained spaces with essential comforts." },
      { id: 4, icon: "MapPin", title: "Convenient Location", description: "Stay close to the experiences and destinations you want to explore." },
      { id: 5, icon: "Users", title: "Personal Experience", description: "A smaller property means more attention to every guest." },
      { id: 6, icon: "MessageCircle", title: "Easy Communication", description: "Contact us directly by WhatsApp, phone or email." },
    ],
  },
  rooms: [
    {
      id: 1, name: "Deluxe Comfort Room", slug: "deluxe-comfort-room",
      tagline: "Comfort, space and a peaceful atmosphere.",
      description: "Perfect for travellers who value comfort, space and a peaceful atmosphere. A calm retreat with everything you need for restful nights.",
      bed_type: "King/Queen Bed", size_sqft: 280, max_guests: 2, price_per_night: "3499.00",
      image: null, is_available: true, is_featured: true,
      amenities: [{ id: 1, icon: "Wifi", name: "Free Wi-Fi" }, { id: 2, icon: "Snowflake", name: "Air Conditioning" }, { id: 3, icon: "Droplets", name: "Hot Water" }, { id: 4, icon: "Tv", name: "Television" }],
    },
    {
      id: 2, name: "Garden View Suite", slug: "garden-view-suite",
      tagline: "Wake up to green, quiet mornings.",
      description: "A spacious suite overlooking the garden, ideal for guests who want extra room to relax and a little more privacy during their stay.",
      bed_type: "King Bed + Sofa", size_sqft: 340, max_guests: 3, price_per_night: "4599.00",
      image: null, is_available: true, is_featured: true,
      amenities: [{ id: 1, icon: "Wifi", name: "Free Wi-Fi" }, { id: 2, icon: "Snowflake", name: "Air Conditioning" }, { id: 5, icon: "Trees", name: "Garden" }, { id: 6, icon: "Sun", name: "Balcony" }],
    },
    {
      id: 3, name: "Family Homestay Room", slug: "family-homestay-room",
      tagline: "Built for family time and shared memories.",
      description: "A generous, warmly furnished room designed for families travelling together, with easy access to shared spaces and a homely feel.",
      bed_type: "Two Queen Beds", size_sqft: 400, max_guests: 4, price_per_night: "5299.00",
      image: null, is_available: true, is_featured: false,
      amenities: [{ id: 1, icon: "Wifi", name: "Free Wi-Fi" }, { id: 2, icon: "Snowflake", name: "Air Conditioning" }, { id: 7, icon: "Car", name: "Parking" }, { id: 8, icon: "ConciergeBell", name: "Room Service" }],
    },
  ],
  amenities: [
    { id: 1, icon: "Wifi", name: "Free Wi-Fi", description: "High-speed internet across the property." },
    { id: 2, icon: "Snowflake", name: "Air Conditioning", description: "Climate control in every room." },
    { id: 3, icon: "Car", name: "Parking", description: "Free on-site private parking." },
    { id: 4, icon: "Coffee", name: "Breakfast", description: "Complimentary breakfast each morning." },
    { id: 5, icon: "Droplets", name: "Hot Water", description: "24-hour hot water supply." },
    { id: 6, icon: "Tv", name: "Television", description: "Smart TV with streaming access." },
    { id: 7, icon: "ConciergeBell", name: "Room Service", description: "On-call room service during the day." },
    { id: 8, icon: "Trees", name: "Garden", description: "A quiet garden to unwind in." },
    { id: 9, icon: "Zap", name: "Power Backup", description: "Uninterrupted power supply." },
    { id: 10, icon: "Sun", name: "Balcony", description: "Private balcony with a view." },
  ],
  images: [],
  video: { title: "A Glimpse of Your Next Escape.", video_url: "", video_file: null, poster_image: null },
  attractions: [
    { id: 1, icon: "Landmark", name: "Discover Local Culture", description: "Explore nearby traditions, markets and experiences.", category: "Culture", distance: "1.5 km" },
    { id: 2, icon: "Waves", name: "Explore Nature", description: "Visit beaches, hills, waterfalls or natural attractions.", category: "Nature", distance: "2.5 km" },
    { id: 3, icon: "UtensilsCrossed", name: "Taste Local Flavours", description: "Discover local food and dining experiences.", category: "Food", distance: "800 m" },
    { id: 4, icon: "Sparkles", name: "Make Every Day Different", description: "Explore something new during your stay.", category: "Experience", distance: "Varies" },
  ],
  testimonials: [
    { id: 1, guest_name: "Ananya Rao", location: "Bengaluru, India", room_stayed: "Deluxe Comfort Room", rating: 5, quote: "The kind of stay that resets you. Quiet, warm and thoughtfully looked after in every detail." },
    { id: 2, guest_name: "James Whitfield", location: "London, UK", room_stayed: "Garden View Suite", rating: 5, quote: "Every corner felt personal. The team went out of their way to make our trip effortless." },
    { id: 3, guest_name: "Meera Nair", location: "Kochi, India", room_stayed: "Family Homestay Room", rating: 5, quote: "Our kids loved it as much as we did. Comfortable, spacious, and genuinely welcoming." },
    { id: 4, guest_name: "Daniel Cho", location: "Seoul, South Korea", room_stayed: "Deluxe Comfort Room", rating: 4, quote: "Peaceful location, excellent hospitality, and a stay we'll remember for a long time." },
  ],
  journey: [
    { step_number: 1, title: "Choose Your Dates", description: "Select your preferred check-in and check-out dates.", icon: "CalendarDays" },
    { step_number: 2, title: "Tell Us Your Preferences", description: "Choose your room and share your travel requirements.", icon: "ClipboardList" },
    { step_number: 3, title: "Confirm Your Stay", description: "Our team confirms availability and assists with your booking.", icon: "CheckCircle2" },
    { step_number: 4, title: "Arrive & Relax", description: "Check in, settle down and enjoy your experience.", icon: "PartyPopper" },
  ],
  faqs: [
    { id: 1, question: "What are the check-in and check-out times?", answer: "Check-in is from 1:00 PM and check-out is by 11:00 AM. Early check-in and late check-out can be arranged on request, subject to availability." },
    { id: 2, question: "How do I confirm availability?", answer: "Submit an enquiry through our booking form, WhatsApp or a phone call, and our team will confirm availability within a few hours." },
    { id: 3, question: "Is breakfast included?", answer: "Yes, complimentary breakfast is included with every stay." },
    { id: 4, question: "Is parking available?", answer: "Yes, free private on-site parking is available for all guests." },
    { id: 5, question: "Can I contact you through WhatsApp?", answer: "Absolutely — tap the WhatsApp button anywhere on the site for a quick response." },
    { id: 6, question: "Are extra beds available?", answer: "Extra beds can be arranged for most rooms on request, subject to availability and a small additional charge." },
    { id: 7, question: "Is Wi-Fi available?", answer: "Yes, complimentary high-speed Wi-Fi is available throughout the property." },
    { id: 8, question: "Can I cancel my booking?", answer: "Yes, cancellations are accepted up to 48 hours before check-in. Please contact our team directly to process a cancellation." },
  ],
  contact: {
    phone: "+91 98765 43210",
    whatsapp_number: "919876543210",
    whatsapp_default_message: "Hi, I would like to check room availability and pricing. Please share more details.",
    email: "hello@cozyhomestay.com",
    address: "123 Palm Grove Road, Coastal Town, Goa, India",
    landmark: "5 minutes from the beach promenade",
  },
  business_hours: [
    { day: "mon", day_display: "Monday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "tue", day_display: "Tuesday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "wed", day_display: "Wednesday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "thu", day_display: "Thursday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "fri", day_display: "Friday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "sat", day_display: "Saturday", open_time: "08:00", close_time: "22:00", is_closed: false },
    { day: "sun", day_display: "Sunday", open_time: "08:00", close_time: "22:00", is_closed: false },
  ],
  maps: {
    embed_url: "https://www.google.com/maps?q=Goa,India&output=embed",
    latitude: "15.2993",
    longitude: "74.1240",
    zoom: 14,
    directions_url: "https://maps.google.com/?q=Goa,India",
  },
  social: [],
};
